development:
  adapter: postgresql
  encoding: unicode
  database: gtm-development
  pool: 5
  username: admin
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: gtm-test
  pool: 5
  username: admin
  password: password
